spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  batch:
    initialize-schema: always
    
logging:
  level:
    org.springframework.batch: debug