spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  batch:
    enabled: true  
    initialize-schema: always

logging:
  level:
    com.springbatchdemo: info
    org.springframework.batch: info